### PR TITLE
Detect.py OpenCV version

### PR DESCRIPTION
**Pull request by davidp94**
I've added a OpenCV version as I got some error when running the gstreamer version on my VirtualBox running Ubuntu on my MacOS

Let me know if I should add documentation or requirements.txt

### CODE REVIEW

**Comment by davidp94** [comment]
I signed it!

**Comment by mtyka** [comment]
This is awesome, thank you!
Could you add a README.md and/or a install_requirements.sh script in the opencv directory with instructions how to install opencv2 - ideally both for raspberry pi and a generic linux box.

**Comment by mtyka** [comment]
Ok, sudo apt install python3-opencv seems to have worked nicely on linux and rpi3/4

**Comment by mtyka** [comment]
Thank you for this contribution - this is awesome !

**Comment by davidp94** [comment]
You’re welcome - couldn’t answer before

Thanks amazing project!

**Pull request merged**
